name: random-name-generator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python job runner"
    runs-on: "ubuntu-latest"
    env:
      PYTHON_VERSION: '3.10.4'
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    strategy:
      matrix:
        python-version: ["3.10.4"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v3"
        with:
          python-version: "${{env.PYTHON_VERSION}}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
          echo "Installation is completed"          

      - name: "Run tox targets for ${{env.PYTHON_VERSION}}"
        run: "python main.py"
      - name: "Docker login"
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: "Docker build"
        run: |
          docker build -t indirk/random-name-generator:1.0.0 .
