name: random-name-generator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python 3.10.4"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.10.4'

    strategy:
      matrix:
        python-version: ["3.10.4"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v3"
        with:
          python-version: "3.10.4"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
          echo "Installation is completed"          

      - name: "Run tox targets for 3.10.4"
        run: "python main.py"